version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./public:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build: docker/php-fpm
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src